<?php
/** Shared catalog for the searchable help and focused generator. @package BuilderShortcodeExtras */
namespace Deckerweb\BuilderShortcodeExtras;
defined( 'ABSPATH' ) || exit;
final class Catalog {
	/** Descriptive metadata only; this method never renders frontend shortcodes. */
	public static function all(): array {
		$catalog = array(
			'bse-nav-menu' => array( 'label' => __('Navigation menu', 'builder-shortcode-extras' ), 'description' => __('Output an existing WordPress navigation menu.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-nav-menu]', 'attributes' => array( 'before', 'after', 'class', 'wrapper', 'menu', 'container', 'container_class', 'container_id', 'menu_class', 'menu_id', 'fallback_cb', 'item_before', 'item_after', 'link_before', 'link_after', 'depth', 'walker', 'theme_location', 'items_wrap', 'item_spacing' ), 'fields' => array(  ) ),
			'bse-item-content' => array( 'label' => __('Embed content', 'builder-shortcode-extras' ), 'description' => __('Reuse a published item by ID; native blocks and supported builders are rendered.', 'builder-shortcode-extras' ), 'group' => __('Essentials', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-item-content id="123"]', 'attributes' => array( 'id', 'css' ), 'fields' => array( array( 'key' => 'id', 'label' => __('Content ID', 'builder-shortcode-extras' ), 'type' => 'number', 'default' => '', 'options' => array(  ) ), array( 'key' => 'css', 'label' => __('Include Elementor CSS', 'builder-shortcode-extras' ), 'type' => 'select', 'default' => 'false', 'options' => array( 'false' => __('No', 'builder-shortcode-extras' ), 'true' => __('Yes', 'builder-shortcode-extras' ) ) ) ) ),
			'bse-comment-form' => array( 'label' => __('Comment form', 'builder-shortcode-extras' ), 'description' => __('Output the WordPress comment form.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-comment-form]', 'attributes' => array( 'before', 'after', 'class', 'wrapper', 'post_id', 'id_form', 'class_form', 'title_reply', 'title_reply_to', 'cancel_reply_link', 'label_submit' ), 'fields' => array(  ) ),
			'bse-elementor-template' => array( 'label' => __('Elementor template', 'builder-shortcode-extras' ), 'description' => __('Embed a saved Elementor template; offered with Elementor Free.', 'builder-shortcode-extras' ), 'group' => __('Integrations', 'builder-shortcode-extras' ), 'integration' => 'Elementor Free', 'example' => '[bse-elementor-template id="123"]', 'attributes' => array( 'id', 'css' ), 'fields' => array(  ) ),
			'bse-genesis-footer' => array( 'label' => __('Genesis footer', 'builder-shortcode-extras' ), 'description' => __('The footer text configured in Genesis.', 'builder-shortcode-extras' ), 'group' => __('Integrations', 'builder-shortcode-extras' ), 'integration' => 'Genesis 3.1+', 'example' => '[bse-genesis-footer]', 'attributes' => array( 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-genesis-breadcrumbs' => array( 'label' => __('Genesis breadcrumbs', 'builder-shortcode-extras' ), 'description' => __('The breadcrumb trail provided by Genesis.', 'builder-shortcode-extras' ), 'group' => __('Integrations', 'builder-shortcode-extras' ), 'integration' => 'Genesis 3.1+', 'example' => '[bse-genesis-breadcrumbs]', 'attributes' => array( 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-copyright' => array( 'label' => __('Copyright', 'builder-shortcode-extras' ), 'description' => __('A copyright notice with the current year.', 'builder-shortcode-extras' ), 'group' => __('Essentials', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-copyright first="2019"]', 'attributes' => array( 'after', 'before', 'copyright', 'first', 'class', 'wrapper' ), 'fields' => array( array( 'key' => 'first', 'label' => __('First year', 'builder-shortcode-extras' ), 'type' => 'number', 'default' => '', 'options' => array(  ) ), array( 'key' => 'before', 'label' => __('Text before', 'builder-shortcode-extras' ), 'type' => 'text', 'default' => '', 'options' => array(  ) ), array( 'key' => 'after', 'label' => __('Text after', 'builder-shortcode-extras' ), 'type' => 'text', 'default' => '', 'options' => array(  ) ), array( 'key' => 'class', 'label' => __('CSS classes (optional)', 'builder-shortcode-extras' ), 'type' => 'text', 'default' => '', 'options' => array() ), array( 'key' => 'wrapper', 'label' => __('Wrapper', 'builder-shortcode-extras' ), 'type' => 'select', 'default' => 'span', 'options' => array( 'span' => 'span', 'p' => 'p', 'div' => 'div', 'small' => 'small' ) ) ) ),
			'bse-site-title' => array( 'label' => __('Site title', 'builder-shortcode-extras' ), 'description' => __('The name of your website.', 'builder-shortcode-extras' ), 'group' => __('Essentials', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-site-title]', 'attributes' => array( 'after', 'before', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-site-slogan' => array( 'label' => __('Site tagline', 'builder-shortcode-extras' ), 'description' => __('The tagline of your website.', 'builder-shortcode-extras' ), 'group' => __('Essentials', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-site-slogan]', 'attributes' => array( 'after', 'before', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-home-link' => array( 'label' => __('Homepage link', 'builder-shortcode-extras' ), 'description' => __('A link to your homepage.', 'builder-shortcode-extras' ), 'group' => __('Essentials', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-home-link]', 'attributes' => array( 'after', 'before', 'text', 'target', 'rel', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-loginout' => array( 'label' => __('Login / logout link', 'builder-shortcode-extras' ), 'description' => __('A link matching the visitor’s login state.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-loginout]', 'attributes' => array( 'after', 'before', 'login_text', 'logout_text', 'login_target', 'logout_target', 'login_redirect', 'logout_redirect', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-site-updated' => array( 'label' => __('Website updated', 'builder-shortcode-extras' ), 'description' => __('The earliest or latest modification of published content.', 'builder-shortcode-extras' ), 'group' => __('Essentials', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-site-updated]', 'attributes' => array( 'before', 'after', 'type', 'label_date', 'date_format', 'label_time', 'time_format', 'tooltip', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-post-count' => array( 'label' => __('Post count', 'builder-shortcode-extras' ), 'description' => __('Count content by post type and status.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-post-count]', 'attributes' => array( 'post_type', 'status', 'before', 'after', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-post-date' => array( 'label' => __('Publication date', 'builder-shortcode-extras' ), 'description' => __('The publication date of the current or selected post.', 'builder-shortcode-extras' ), 'group' => __('Essentials', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-post-date]', 'attributes' => array( 'after', 'before', 'post_id', 'format', 'label', 'relative_depth', 'class', 'wrapper' ), 'fields' => array( array( 'key' => 'post_id', 'label' => __('Post ID (optional)', 'builder-shortcode-extras' ), 'type' => 'number', 'default' => '', 'options' => array(  ) ), array( 'key' => 'format', 'label' => __('Date format', 'builder-shortcode-extras' ), 'type' => 'select', 'default' => '', 'options' => array( '' => __('Website default', 'builder-shortcode-extras' ), 'd.m.Y' => __('31.12.2026', 'builder-shortcode-extras' ), 'F j, Y' => __('December 31, 2026', 'builder-shortcode-extras' ), 'Y-m-d' => __('2026-12-31', 'builder-shortcode-extras' ), 'relative' => __('Relative date', 'builder-shortcode-extras' ) ) ), array( 'key' => 'label', 'label' => __('Label', 'builder-shortcode-extras' ), 'type' => 'text', 'default' => '', 'options' => array(  ) ), array( 'key' => 'class', 'label' => __('CSS classes (optional)', 'builder-shortcode-extras' ), 'type' => 'text', 'default' => '', 'options' => array() ), array( 'key' => 'wrapper', 'label' => __('Wrapper', 'builder-shortcode-extras' ), 'type' => 'select', 'default' => 'span', 'options' => array( 'span' => 'span', 'p' => 'p', 'div' => 'div', 'small' => 'small' ) ) ) ),
			'bse-post-time' => array( 'label' => __('Publication time', 'builder-shortcode-extras' ), 'description' => __('The publication time of the current or selected post.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-post-time]', 'attributes' => array( 'after', 'before', 'post_id', 'format', 'label', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-post-modified-date' => array( 'label' => __('Last updated', 'builder-shortcode-extras' ), 'description' => __('The modification date of the current or selected post.', 'builder-shortcode-extras' ), 'group' => __('Essentials', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-post-modified-date]', 'attributes' => array( 'after', 'before', 'post_id', 'format', 'label', 'relative_depth', 'class', 'wrapper' ), 'fields' => array( array( 'key' => 'post_id', 'label' => __('Post ID (optional)', 'builder-shortcode-extras' ), 'type' => 'number', 'default' => '', 'options' => array(  ) ), array( 'key' => 'format', 'label' => __('Date format', 'builder-shortcode-extras' ), 'type' => 'select', 'default' => '', 'options' => array( '' => __('Website default', 'builder-shortcode-extras' ), 'd.m.Y' => __('31.12.2026', 'builder-shortcode-extras' ), 'F j, Y' => __('December 31, 2026', 'builder-shortcode-extras' ), 'Y-m-d' => __('2026-12-31', 'builder-shortcode-extras' ), 'relative' => __('Relative date', 'builder-shortcode-extras' ) ) ), array( 'key' => 'label', 'label' => __('Label', 'builder-shortcode-extras' ), 'type' => 'text', 'default' => '', 'options' => array(  ) ), array( 'key' => 'class', 'label' => __('CSS classes (optional)', 'builder-shortcode-extras' ), 'type' => 'text', 'default' => '', 'options' => array() ), array( 'key' => 'wrapper', 'label' => __('Wrapper', 'builder-shortcode-extras' ), 'type' => 'select', 'default' => 'span', 'options' => array( 'span' => 'span', 'p' => 'p', 'div' => 'div', 'small' => 'small' ) ) ) ),
			'bse-item-last-updated' => array( 'label' => __('Last updated (alias)', 'builder-shortcode-extras' ), 'description' => __('An alias for bse-post-modified-date.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-item-last-updated]', 'attributes' => array( 'after', 'before', 'post_id', 'format', 'label', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-post-modified-time' => array( 'label' => __('Last updated time', 'builder-shortcode-extras' ), 'description' => __('The modification time of the current or selected post.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-post-modified-time]', 'attributes' => array( 'after', 'before', 'post_id', 'format', 'label', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-post-author' => array( 'label' => __('Post author', 'builder-shortcode-extras' ), 'description' => __('The author’s display name.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-post-author]', 'attributes' => array( 'after', 'before', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-post-author-link' => array( 'label' => __('Author website link', 'builder-shortcode-extras' ), 'description' => __('The author’s name linked to their website.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-post-author-link]', 'attributes' => array( 'after', 'before', 'target', 'rel', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-post-author-posts-link' => array( 'label' => __('Author archive link', 'builder-shortcode-extras' ), 'description' => __('The author’s name linked to their archive.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-post-author-posts-link]', 'attributes' => array( 'after', 'before', 'target', 'rel', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-post-tags' => array( 'label' => __('Post tags', 'builder-shortcode-extras' ), 'description' => __('The tags assigned to the current post.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-post-tags]', 'attributes' => array( 'after', 'before', 'sep', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-post-categories' => array( 'label' => __('Post categories', 'builder-shortcode-extras' ), 'description' => __('The categories assigned to the current post.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-post-categories]', 'attributes' => array( 'sep', 'before', 'after', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-post-terms' => array( 'label' => __('Taxonomy terms', 'builder-shortcode-extras' ), 'description' => __('Terms from a selected taxonomy.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-post-terms]', 'attributes' => array( 'after', 'before', 'sep', 'taxonomy', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-post-edit' => array( 'label' => __('Edit post link', 'builder-shortcode-extras' ), 'description' => __('An edit link for visitors with editing permission.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-post-edit]', 'attributes' => array( 'after', 'before', 'label', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-post-link' => array( 'label' => __('Post / page link', 'builder-shortcode-extras' ), 'description' => __('Link to an item by ID or slug, or to the privacy policy.', 'builder-shortcode-extras' ), 'group' => __('Essentials', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-post-link id="123"]', 'attributes' => array( 'id', 'slug', 'post_type', 'privacy', 'text', 'target', 'rel', 'before', 'after', 'class', 'wrapper' ), 'fields' => array( array( 'key' => 'id', 'label' => __('Post ID', 'builder-shortcode-extras' ), 'type' => 'number', 'default' => '', 'options' => array(  ) ), array( 'key' => 'text', 'label' => __('Link text (optional)', 'builder-shortcode-extras' ), 'type' => 'text', 'default' => '', 'options' => array(  ) ), array( 'key' => 'class', 'label' => __('CSS classes (optional)', 'builder-shortcode-extras' ), 'type' => 'text', 'default' => '', 'options' => array() ), array( 'key' => 'wrapper', 'label' => __('Wrapper', 'builder-shortcode-extras' ), 'type' => 'select', 'default' => 'span', 'options' => array( 'span' => 'span', 'p' => 'p', 'div' => 'div', 'small' => 'small' ) ) ) ),
			'bse-user' => array( 'label' => __('User information', 'builder-shortcode-extras' ), 'description' => __('A selected user field with an optional fallback.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-user]', 'attributes' => array( 'user_id', 'field', 'default', 'before', 'after', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-userid' => array( 'label' => __('Current user ID', 'builder-shortcode-extras' ), 'description' => __('The ID of the signed-in user.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-userid]', 'attributes' => array(  ), 'fields' => array(  ) ),
			'bse-email' => array( 'label' => __('Current user email', 'builder-shortcode-extras' ), 'description' => __('The email address of the signed-in user.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-email]', 'attributes' => array(  ), 'fields' => array(  ) ),
			'bse-login' => array( 'label' => __('Current user login', 'builder-shortcode-extras' ), 'description' => __('The login name of the signed-in user.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-login]', 'attributes' => array(  ), 'fields' => array(  ) ),
			'bse-displayname' => array( 'label' => __('Current user name', 'builder-shortcode-extras' ), 'description' => __('The display name of the signed-in user.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-displayname]', 'attributes' => array(  ), 'fields' => array(  ) ),
			'bse-firstname' => array( 'label' => __('Current user first name', 'builder-shortcode-extras' ), 'description' => __('The first name of the signed-in user.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-firstname]', 'attributes' => array(  ), 'fields' => array(  ) ),
			'bse-lastname' => array( 'label' => __('Current user last name', 'builder-shortcode-extras' ), 'description' => __('The last name of the signed-in user.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-lastname]', 'attributes' => array(  ), 'fields' => array(  ) ),
			'bse-version' => array( 'label' => __('Version information', 'builder-shortcode-extras' ), 'description' => __('Technical version information for documentation and support.', 'builder-shortcode-extras' ), 'group' => __('More helpers', 'builder-shortcode-extras' ), 'integration' => '', 'example' => '[bse-version]', 'attributes' => array( 'type', 'plugin', 'constant', 'custom', 'before', 'after', 'class', 'wrapper' ), 'fields' => array(  ) ),
			'bse-wpblock' => array( 'label' => __('Synced pattern', 'builder-shortcode-extras' ), 'description' => __('Embed a WordPress synced pattern by ID.', 'builder-shortcode-extras' ), 'group' => __('Integrations', 'builder-shortcode-extras' ), 'integration' => 'WordPress synced patterns', 'example' => '[bse-wpblock id="123"]', 'attributes' => array( 'id', 'css' ), 'fields' => array(  ) ),
			'bse-astra-layout' => array( 'label' => __('Astra layout', 'builder-shortcode-extras' ), 'description' => __('Embed an Astra Pro custom layout by ID.', 'builder-shortcode-extras' ), 'group' => __('Integrations', 'builder-shortcode-extras' ), 'integration' => 'Astra Pro custom layouts', 'example' => '[bse-astra-layout id="123"]', 'attributes' => array( 'id', 'css' ), 'fields' => array(  ) ),
		);
		$order = array( 'bse-copyright', 'bse-post-date', 'bse-post-modified-date', 'bse-post-link', 'bse-item-content' );
		$first = array();
		foreach ( $order as $tag ) { $first[$tag] = $catalog[$tag]; }
		return $first + $catalog;
	}
}
